### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by FelixHaller** [FelixHaller/windy-oak#14]

**Comment by einbit** [comment]
Folgende Änderungen sind zu erledigen:
- Datenbankänderung +Anpassung dbscript
- createProject, updateProject in StoreServiceSQLite und in ProjectsResourceImpl
- Regulärer Ausdruck für createProject und UpdateProject, da mehrere Tags angegeben werden sollen
- Suchfunktion für Project --> searchProjectsByTag in StoreServiceSQLite, Einbinden der QueryParam in ProjectsResourceImpl und ProjectsResource.

**Comment by einbit** [comment]
Mit Merge von Issue14:
- Tags sind in REST und CORE mit eingebaut (inklusive Datenbankabfragen in StoreServiceInSQL)
- getTag, getTags, updateTag, createTag, deleteTag. Bei deleteTag fehlt noch die Abfrage ob der Tag in einem Project verwendet wird. Dazu muss erst die Suchfunktion "Projects über Tags suchen" implementiert werden.

**Comment by einbit** [comment]
Mit Merge Issue14v2:
- Datenbankänderungen
- Beispieltags für Projects

**Comment by einbit** [comment]
Issue 14v3:
Implementierung Tag in createProject und updateProject.
