### ISSUE TITLE
Bei createProject tagName-Parameterangabe freiwillig?

### ISSUE THREAD

**Issue by einbit** [FelixHaller/windy-oak#19]
Im Moment ist es so implementiert, dass mind. ein Tag angegeben werden muss. Was soll ein Projekt ohne Tag? Zur Not können wir einen Tag "Leer" oder so ähnlich erstellen.

**Comment by FelixHaller** [comment]
Bitte auch ermöglichen, dass Projekte ohne Tag angelegt werden können.
